services:
  - type: web
    name: mcx-aluminium-scraper
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 4 --threads 2 --worker-tmp-dir /dev/shm app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
