services:
  - type: web
    name: mcx-aluminium-scraper
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 4 --threads 2 --worker-tmp-dir /dev/shm wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: S7I7jw5E7vxkLKe72239935d39cd65878c9788631e
        sync: false
    buildFilter:
      paths:
        - requirements.txt
        - app.py
        - wsgi.py
